# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PrivyApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PrivyApp

  target 'PrivyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'PrivyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PrivyApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!



end
